import type { Metadata } from "next";
import { Inter } from "next/font/google";

import localFont from "next/font/local";
import "@/styles/globals.scss";
import "./page.css";
import Header from "@/components/Header";
import RecoilRootProvider from "@/provider/RecoilProvider";

const inter = Inter({ subsets: ["latin"] });

const sagak = localFont({
  src: [
    {
      path: "../fonts/sagak.ttf",
      weight: "normal",
      style: "normal",
    },
    // {
    //   path: "../fonts/sagak.ttf",
    //   weight: "500",
    //   style: "normal",
    // },
    // {
    //   path: "../fonts/sagak.ttf",
    //   weight: "700",
    //   style: "normal",
    // },
  ],
  variable: "--font-sagak",
  display: "fallback",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sagak.variable}>
        {" "}
        <Header />
        <RecoilRootProvider>{children}</RecoilRootProvider>
      </body>
    </html>
  );
}
